sudo: required
dist: trusty

language: go

go:
  - 1.6
  - 1.7
  - 1.8
  - tip

services:
  - rabbitmq

before_script:
  - ./bin/ci/install_on_debian.sh
  - ./bin/ci/before_build.sh

script: make

matrix:
  allow_failures:
    - go: tip

notifications:
  email:
    - michael@rabbitmq.com
